spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
logging:
  level:
    com.example.mike.bookmanager: DEBUG
  file:
    name: application.log
